version: 0.2
phases:
  build:
    commands:
      - ./gradlew zipAll
artifacts:
  files:
    - build/distributions/lambda-test-*.zip  # Path to the generated zip file
  discard-paths: yes  # Keep the file flat (no directory structure)
cache:
  paths:
    - '/root/.gradle/**/*'
