version: 0.2
phases:
  build:
    commands:
      - echo "Building the Java Lambda package..."
      - ./gradlew clean zipAll
  post_build:
      commands:
        - ARTIFACT_NAME=$(basename $(find build/distributions -type f -name "*.zip" -print -quit))

        - echo "Uploading $ARTIFACT_NAME to $LAMBDA_ARTIFACTS_BUCKET/$LAMBDA_ARTIFACTS_KEY/"
        - aws s3 cp build/distributions/$ARTIFACT_NAME s3://$LAMBDA_ARTIFACTS_BUCKET/$LAMBDA_ARTIFACTS_KEY/

        - echo "Deploying $ARTIFACT_NAME to $LAMBDA_FUNCTION_NAME"
        - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $LAMBDA_ARTIFACTS_BUCKET --s3-key $LAMBDA_ARTIFACTS_KEY/$ARTIFACT_NAME
cache:
  paths:
    - '/root/.gradle/**/*'
