Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda Pipeline Test
Resources:
  LambdaTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaTest
      Handler: LambdaEntry::handleRequest
      Runtime: java17
      CodeUri: distributions/lambda-test-1.0-SNAPSHOT.zip

