Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda Pipeline Test
Resources:
  LambdaTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaTest
      Handler: com.drucks.LambdaEntry::handleRequest
      Runtime: java11
      CodeUri: ./

